# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin_try.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(710, 597)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/Vector-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setWindowOpacity(1.0)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(600, 3600))
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setStyleSheet("background-color: #d1e8ef\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(4, 5, 4, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_algorithm = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_algorithm.sizePolicy().hasHeightForWidth())
        self.pushButton_algorithm.setSizePolicy(sizePolicy)
        self.pushButton_algorithm.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_algorithm.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_algorithm.setStyleSheet("QPushButton {\n"
"    \n"
"    image: url(:/icon/icon/algorithm.svg);\n"
"}\n"
"QPushButton {\n"
"    padding: 0;\n"
"    border: None;\n"
"}\n"
"/*悬停*/\n"
"QPushButton:hover {\n"
"    background-color: #e0e0e0;\n"
"    border-color: #999999;\n"
"}\n"
"\n"
"/* 按下 */\n"
"QPushButton:pressed {\n"
"    background-color: #d0d0d0;\n"
"}")
        self.pushButton_algorithm.setText("")
        self.pushButton_algorithm.setObjectName("pushButton_algorithm")
        self.gridLayout_2.addWidget(self.pushButton_algorithm, 3, 0, 1, 1)
        self.toolButtonBack = QtWidgets.QToolButton(self.frame_2)
        self.toolButtonBack.setMaximumSize(QtCore.QSize(30, 30))
        self.toolButtonBack.setStyleSheet("QToolButton {\n"
"    image: url(:/icon/icon/back.svg);\n"
"}\n"
"QToolButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 3;\n"
"}\n"
"/*悬停*/\n"
"QToolButton:hover {\n"
"    background-color: #e0e0e0;\n"
"    border-color: #999999;\n"
"}\n"
"\n"
"/* 按下 */\n"
"QToolButton:pressed {\n"
"    background-color: #d0d0d0;\n"
"}\n"
"")
        self.toolButtonBack.setText("")
        self.toolButtonBack.setObjectName("toolButtonBack")
        self.gridLayout_2.addWidget(self.toolButtonBack, 0, 0, 1, 1)
        self.label_function = QtWidgets.QLabel(self.frame_2)
        self.label_function.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_function.setObjectName("label_function")
        self.gridLayout_2.addWidget(self.label_function, 4, 1, 1, 1)
        self.pushButton_more = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_more.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_more.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_more.setStyleSheet("QPushButton {\n"
"    \n"
"    image: url(:/icon/icon/more.svg);\n"
"}\n"
"QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 5;\n"
"}\n"
"/*悬停*/\n"
"QPushButton:hover {\n"
"    background-color: #e0e0e0;\n"
"    border-color: #999999;\n"
"}\n"
"\n"
"/* 按下 */\n"
"QPushButton:pressed {\n"
"    background-color: #d0d0d0;\n"
"}")
        self.pushButton_more.setText("")
        self.pushButton_more.setObjectName("pushButton_more")
        self.gridLayout_2.addWidget(self.pushButton_more, 5, 0, 1, 1)
        self.label_algorithm = QtWidgets.QLabel(self.frame_2)
        self.label_algorithm.setObjectName("label_algorithm")
        self.gridLayout_2.addWidget(self.label_algorithm, 3, 1, 1, 1)
        self.label_more = QtWidgets.QLabel(self.frame_2)
        self.label_more.setObjectName("label_more")
        self.gridLayout_2.addWidget(self.label_more, 5, 1, 1, 1)
        self.pushButton_function = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_function.sizePolicy().hasHeightForWidth())
        self.pushButton_function.setSizePolicy(sizePolicy)
        self.pushButton_function.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_function.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_function.setStyleSheet("QPushButton {\n"
"    image: url(:/icon/icon/function.svg);\n"
"}\n"
"QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 3;\n"
"}\n"
"/*悬停*/\n"
"QPushButton:hover {\n"
"    background-color: #e0e0e0;\n"
"    border-color: #999999;\n"
"}\n"
"\n"
"/* 按下 */\n"
"QPushButton:pressed {\n"
"    background-color: #d0d0d0;\n"
"}")
        self.pushButton_function.setText("")
        self.pushButton_function.setObjectName("pushButton_function")
        self.gridLayout_2.addWidget(self.pushButton_function, 4, 0, 1, 1)
        self.toolButtonSettings = QtWidgets.QToolButton(self.frame_2)
        self.toolButtonSettings.setMinimumSize(QtCore.QSize(30, 30))
        self.toolButtonSettings.setMaximumSize(QtCore.QSize(50, 50))
        self.toolButtonSettings.setStyleSheet("QToolButton{\n"
"    image: url(:/icon/icon/setting.svg);\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 3;\n"
"}\n"
"/*悬停*/\n"
"QToolButton:hover {\n"
"    background-color: #e0e0e0;\n"
"    border-color: #999999;\n"
"}\n"
"\n"
"/* 按下 */\n"
"QToolButton:pressed {\n"
"    background-color: #d0d0d0;\n"
"}\n"
"")
        self.toolButtonSettings.setText("")
        self.toolButtonSettings.setObjectName("toolButtonSettings")
        self.gridLayout_2.addWidget(self.toolButtonSettings, 8, 0, 1, 1)
        self.label_settings = QtWidgets.QLabel(self.frame_2)
        self.label_settings.setObjectName("label_settings")
        self.gridLayout_2.addWidget(self.label_settings, 8, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setMaximumSize(QtCore.QSize(40, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 38, 372))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 6, 0, 1, 1)
        self.toolButtonRightOpen = QtWidgets.QToolButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonRightOpen.sizePolicy().hasHeightForWidth())
        self.toolButtonRightOpen.setSizePolicy(sizePolicy)
        self.toolButtonRightOpen.setMinimumSize(QtCore.QSize(40, 30))
        self.toolButtonRightOpen.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButtonRightOpen.setStyleSheet("QToolButton{\n"
"    image: url(:/icon/icon/toggle-right.svg)\n"
"}\n"
"QToolButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 1;\n"
"}\n"
"/*悬停*/\n"
"QToolButton:hover {\n"
"    background-color: #e0e0e0;\n"
"    border-color: #999999;\n"
"}\n"
"\n"
"/* 按下 */\n"
"QToolButton:pressed {\n"
"    background-color: #d0d0d0;\n"
"}\n"
"\n"
"")
        self.toolButtonRightOpen.setText("")
        self.toolButtonRightOpen.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButtonRightOpen.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButtonRightOpen.setArrowType(QtCore.Qt.NoArrow)
        self.toolButtonRightOpen.setObjectName("toolButtonRightOpen")
        self.gridLayout_2.addWidget(self.toolButtonRightOpen, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
        self.stackedWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(528, 481))
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setMidLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_algorithm = QtWidgets.QWidget()
        self.page_algorithm.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_algorithm.sizePolicy().hasHeightForWidth())
        self.page_algorithm.setSizePolicy(sizePolicy)
        self.page_algorithm.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.page_algorithm.setObjectName("page_algorithm")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_algorithm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_algorithm = QtWidgets.QFrame(self.page_algorithm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_algorithm.sizePolicy().hasHeightForWidth())
        self.frame_algorithm.setSizePolicy(sizePolicy)
        self.frame_algorithm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_algorithm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_algorithm.setObjectName("frame_algorithm")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_algorithm)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_select_problems = QtWidgets.QGroupBox(self.frame_algorithm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_select_problems.sizePolicy().hasHeightForWidth())
        self.groupBox_select_problems.setSizePolicy(sizePolicy)
        self.groupBox_select_problems.setObjectName("groupBox_select_problems")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_select_problems)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_single_obj = QtWidgets.QRadioButton(self.groupBox_select_problems)
        self.radioButton_single_obj.setObjectName("radioButton_single_obj")
        self.horizontalLayout_3.addWidget(self.radioButton_single_obj)
        self.radioButton_multi_obj = QtWidgets.QRadioButton(self.groupBox_select_problems)
        self.radioButton_multi_obj.setObjectName("radioButton_multi_obj")
        self.horizontalLayout_3.addWidget(self.radioButton_multi_obj)
        self.horizontalLayout_2.addWidget(self.groupBox_select_problems)
        self.groupBox_select_algorithm = QtWidgets.QGroupBox(self.frame_algorithm)
        self.groupBox_select_algorithm.setObjectName("groupBox_select_algorithm")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_select_algorithm)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_algorithm_text = QtWidgets.QLabel(self.groupBox_select_algorithm)
        self.label_algorithm_text.setObjectName("label_algorithm_text")
        self.horizontalLayout_4.addWidget(self.label_algorithm_text)
        self.comboBox_algorithm = QtWidgets.QComboBox(self.groupBox_select_algorithm)
        self.comboBox_algorithm.setObjectName("comboBox_algorithm")
        self.comboBox_algorithm.addItem("")
        self.comboBox_algorithm.addItem("")
        self.comboBox_algorithm.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_algorithm)
        self.toolButton_algorithm = QtWidgets.QToolButton(self.groupBox_select_algorithm)
        self.toolButton_algorithm.setStyleSheet("QToolButton {\n"
"    image: url(:/icon/icon/file_input.svg);\n"
"}\n"
"QToolButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 3;\n"
"}\n"
"/*悬停*/\n"
"QToolButton:hover {\n"
"    background-color: #e0e0e0;\n"
"    border-color: #999999;\n"
"}\n"
"\n"
"/* 按下 */\n"
"QToolButton:pressed {\n"
"    background-color: #d0d0d0;\n"
"}\n"
"")
        self.toolButton_algorithm.setText("")
        self.toolButton_algorithm.setObjectName("toolButton_algorithm")
        self.horizontalLayout_4.addWidget(self.toolButton_algorithm)
        self.horizontalLayout_2.addWidget(self.groupBox_select_algorithm)
        self.verticalLayout_3.addWidget(self.frame_algorithm)
        self.tabWidget = QtWidgets.QTabWidget(self.page_algorithm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textBrowser_algorithm_introduce = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_algorithm_introduce.setStyleSheet("QTextBrowser {\n"
"                background-color: #f8f9fa;\n"
"                border: 1px solid #e1e4e8;\n"
"                border-radius: 4px;\n"
"                padding: 10px;\n"
"                font-family: \'Segoe UI\', Arial, sans-serif;\n"
"}\n"
"a {\n"
"                color: #0366d6;\n"
"                text-decoration: none;\n"
"}\n"
"a:hover {\n"
"                text-decoration: underline;\n"
"}")
        self.textBrowser_algorithm_introduce.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_algorithm_introduce.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textBrowser_algorithm_introduce.setObjectName("textBrowser_algorithm_introduce")
        self.verticalLayout_4.addWidget(self.textBrowser_algorithm_introduce)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 536, 357))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_popSize = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_popSize.setObjectName("label_popSize")
        self.gridLayout_3.addWidget(self.label_popSize, 0, 0, 1, 1)
        self.lineEdit_popSize = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_popSize.setObjectName("lineEdit_popSize")
        self.gridLayout_3.addWidget(self.lineEdit_popSize, 0, 1, 1, 1)
        self.label_mutate_rate = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_mutate_rate.setObjectName("label_mutate_rate")
        self.gridLayout_3.addWidget(self.label_mutate_rate, 1, 0, 1, 1)
        self.lineEdit_mutate_rate = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_mutate_rate.setObjectName("lineEdit_mutate_rate")
        self.gridLayout_3.addWidget(self.lineEdit_mutate_rate, 1, 1, 1, 1)
        self.label_cross_rate = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_cross_rate.setObjectName("label_cross_rate")
        self.gridLayout_3.addWidget(self.label_cross_rate, 2, 0, 1, 1)
        self.lineEdit_cross_rate = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_cross_rate.setObjectName("lineEdit_cross_rate")
        self.gridLayout_3.addWidget(self.lineEdit_cross_rate, 2, 1, 1, 1)
        self.label_max_iterations = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_max_iterations.setObjectName("label_max_iterations")
        self.gridLayout_3.addWidget(self.label_max_iterations, 3, 0, 1, 1)
        self.lineEdit_max_iterations = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_max_iterations.setObjectName("lineEdit_max_iterations")
        self.gridLayout_3.addWidget(self.lineEdit_max_iterations, 3, 1, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.stackedWidget.addWidget(self.page_algorithm)
        self.page_function = QtWidgets.QWidget()
        self.page_function.setObjectName("page_function")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_function)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_object_fun = QtWidgets.QGroupBox(self.page_function)
        self.groupBox_object_fun.setObjectName("groupBox_object_fun")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_object_fun)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_object_fun = QtWidgets.QComboBox(self.groupBox_object_fun)
        self.comboBox_object_fun.setObjectName("comboBox_object_fun")
        self.gridLayout_4.addWidget(self.comboBox_object_fun, 1, 0, 1, 1)
        self.toolButton_object_fun_input = QtWidgets.QToolButton(self.groupBox_object_fun)
        self.toolButton_object_fun_input.setStyleSheet("QToolButton {\n"
"    image: url(:/icon/icon/file_input.svg);\n"
"}\n"
"QToolButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 3;\n"
"}\n"
"/*悬停*/\n"
"QToolButton:hover {\n"
"    background-color: #e0e0e0;\n"
"    border-color: #999999;\n"
"}\n"
"\n"
"/* 按下 */\n"
"QToolButton:pressed {\n"
"    background-color: #d0d0d0;\n"
"}")
        self.toolButton_object_fun_input.setText("")
        self.toolButton_object_fun_input.setObjectName("toolButton_object_fun_input")
        self.gridLayout_4.addWidget(self.toolButton_object_fun_input, 1, 1, 1, 1)
        self.label_object_fun = QtWidgets.QLabel(self.groupBox_object_fun)
        self.label_object_fun.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_object_fun.setObjectName("label_object_fun")
        self.gridLayout_4.addWidget(self.label_object_fun, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_object_fun)
        self.groupBox_constraint = QtWidgets.QGroupBox(self.page_function)
        self.groupBox_constraint.setObjectName("groupBox_constraint")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_constraint)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.comboBox_constraint = QtWidgets.QComboBox(self.groupBox_constraint)
        self.comboBox_constraint.setObjectName("comboBox_constraint")
        self.gridLayout_5.addWidget(self.comboBox_constraint, 3, 1, 1, 1)
        self.label_constraint = QtWidgets.QLabel(self.groupBox_constraint)
        self.label_constraint.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_constraint.setObjectName("label_constraint")
        self.gridLayout_5.addWidget(self.label_constraint, 2, 1, 1, 1)
        self.label_bounds = QtWidgets.QLabel(self.groupBox_constraint)
        self.label_bounds.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_bounds.setObjectName("label_bounds")
        self.gridLayout_5.addWidget(self.label_bounds, 0, 1, 1, 1)
        self.toolButton_constraint_input = QtWidgets.QToolButton(self.groupBox_constraint)
        self.toolButton_constraint_input.setStyleSheet("QToolButton {\n"
"    image: url(:/icon/icon/file_input.svg);\n"
"}\n"
"QToolButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 3;\n"
"}\n"
"/*悬停*/\n"
"QToolButton:hover {\n"
"    background-color: #e0e0e0;\n"
"    border-color: #999999;\n"
"}\n"
"\n"
"/* 按下 */\n"
"QToolButton:pressed {\n"
"    background-color: #d0d0d0;\n"
"}")
        self.toolButton_constraint_input.setText("")
        self.toolButton_constraint_input.setObjectName("toolButton_constraint_input")
        self.gridLayout_5.addWidget(self.toolButton_constraint_input, 3, 2, 1, 1)
        self.lineEdit_bounds = QtWidgets.QLineEdit(self.groupBox_constraint)
        self.lineEdit_bounds.setMaximumSize(QtCore.QSize(600, 16777215))
        self.lineEdit_bounds.setObjectName("lineEdit_bounds")
        self.gridLayout_5.addWidget(self.lineEdit_bounds, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_constraint)
        self.groupBox = QtWidgets.QGroupBox(self.page_function)
        self.groupBox.setObjectName("groupBox")
        self.buttonBox_running = QtWidgets.QDialogButtonBox(self.groupBox)
        self.buttonBox_running.setGeometry(QtCore.QRect(390, 120, 156, 23))
        self.buttonBox_running.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_running.setObjectName("buttonBox_running")
        self.verticalLayout_6.addWidget(self.groupBox)
        self.stackedWidget.addWidget(self.page_function)
        self.page_more = QtWidgets.QWidget()
        self.page_more.setObjectName("page_more")
        self.stackedWidget.addWidget(self.page_more)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setObjectName("page_settings")
        self.stackedWidget.addWidget(self.page_settings)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.widget_operation_inf = QtWidgets.QWidget(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_operation_inf.sizePolicy().hasHeightForWidth())
        self.widget_operation_inf.setSizePolicy(sizePolicy)
        self.widget_operation_inf.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_operation_inf.setMaximumSize(QtCore.QSize(16777215, 350))
        self.widget_operation_inf.setObjectName("widget_operation_inf")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_operation_inf)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser_operation_history = QtWidgets.QTextBrowser(self.widget_operation_inf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textBrowser_operation_history.sizePolicy().hasHeightForWidth())
        self.textBrowser_operation_history.setSizePolicy(sizePolicy)
        self.textBrowser_operation_history.setMinimumSize(QtCore.QSize(0, 30))
        self.textBrowser_operation_history.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textBrowser_operation_history.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_operation_history.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_operation_history.setLineWidth(1)
        self.textBrowser_operation_history.setMidLineWidth(1)
        self.textBrowser_operation_history.setObjectName("textBrowser_operation_history")
        self.horizontalLayout.addWidget(self.textBrowser_operation_history)
        self.verticalLayout.addWidget(self.widget_operation_inf)
        self.gridLayout.addWidget(self.frame_3, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.widget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_function.setText(_translate("Form", "函数约束"))
        self.label_algorithm.setText(_translate("Form", "优化算法"))
        self.label_more.setText(_translate("Form", "more"))
        self.label_settings.setText(_translate("Form", "设置"))
        self.groupBox_select_problems.setTitle(_translate("Form", "优化问题选择"))
        self.radioButton_single_obj.setText(_translate("Form", "单目标优化"))
        self.radioButton_multi_obj.setText(_translate("Form", "多目标优化"))
        self.groupBox_select_algorithm.setTitle(_translate("Form", "优化算法选择"))
        self.label_algorithm_text.setText(_translate("Form", "xxx"))
        self.comboBox_algorithm.setItemText(0, _translate("Form", "DE"))
        self.comboBox_algorithm.setItemText(1, _translate("Form", "PSO"))
        self.comboBox_algorithm.setItemText(2, _translate("Form", "GA"))
        self.textBrowser_algorithm_introduce.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\',\'Arial\',\'sans-serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "优化算法"))
        self.label_popSize.setText(_translate("Form", "popSize:"))
        self.label_mutate_rate.setText(_translate("Form", "mutate rate:"))
        self.label_cross_rate.setText(_translate("Form", "cross rate:"))
        self.label_max_iterations.setText(_translate("Form", "maximum iterations:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "约束参数设置"))
        self.groupBox_object_fun.setTitle(_translate("Form", "目标函数"))
        self.label_object_fun.setText(_translate("Form", "目标函数设置"))
        self.groupBox_constraint.setTitle(_translate("Form", "约束函数"))
        self.label_constraint.setText(_translate("Form", "约束函数选择："))
        self.label_bounds.setText(_translate("Form", "边界设置："))
        self.groupBox.setTitle(_translate("Form", "运算"))


from resources import resources_rc
